### ISSUE TITLE
High CPU load starting with 1.0.0

### ISSUE THREAD

**Issue by thisisthekap** [arafato/azurite#107]
After upgrading to 1.0.0 we are experiencing high idle loads (tested both with the latest Docker for mac and Docker Toolbox for Windows)

The issue applies also to 1.1.0

**Comment by arafato** [comment]
Hi @thisisthekap , thanks for reporting! Starting with 1.0.0 Azurite started to introduce support for Azure Storage Queues. Two separate processes (one for blob, one for queue) are now forked by the main Azurite process to spread the load onto different cores. 

There seems to be an unexpected side-effect with Docker. 
We will investigate in the next few days and provide a fix asap. Will update you here as soon as it is published and/or come back with follow-up questions.

**Comment by arafato** [comment]
Hi @thisisthekap , thanks for reporting! Starting with 1.0.0 Azurite started to introduce support for Azure Storage Queues. Two separate processes (one for blob, one for queue) are now forked by the main Azurite process to spread the load onto different cores. 

There seems to be an unexpected side-effect with Docker. 
We will investigate in the next few days and provide a fix asap. Will update you here as soon as it is published and/or come back with follow-up questions.

**Comment by arafato** [comment]
This is related to #110. Fix is already submitted and will be released as v1.2.0 in the next few hours.
