### ISSUE TITLE
Extend Dockerfile to support different executable (e.g. azurite-blob)

### ISSUE THREAD

**Issue by thisisthekap** [arafato/azurite#111]
I would like to optionally specify the executable to e.g. just start the blob storage emulator.

### Default usage

`docker run -d -t -p 10000:10000 -v /path/to/folder:/opt/azurite/folder arafato/azurite`

### Blob storage only

`docker run -d -t -p 10000:10000 -e "executable=azurite-blob" -v /path/to/folder:/opt/azurite/folder arafato/azurite`

@arafato If you like, I could take care about that myself and submit a PR.

**Comment by arafato** [comment]
@thisisthekap this would be really great! Will you also take care of the storage queue emulator? It is listening on port 10001.

**Comment by thisisthekap** [comment]
Yes, I am also going to expose this port.

On 23.11.2017, at 22:27, Oliver Arafat <notifications@github.com<mailto:notifications@github.com>> wrote:


@thisisthekap<https://github.com/thisisthekap> this would be really great! Will you also take care of the storage queue emulator? It is listening on port 10001.

-

**Comment by arafato** [comment]
@thisisthekap thank you so much, this is really great! Starting with version 1.3.2 this will be included in every Docker image.
