### ISSUE TITLE
table storage implementation

### ISSUE THREAD

**Issue by wellDan28** [arafato/azurite#114]
Hey, I want to suggest to add a table storage implementation. I would happy to help implement it.

**Comment by arafato** [comment]
hi @wellDan28 ! This would be really appreciated! How can I help you to get up speed with Azurite development? I could start a Wiki which describes the repo structure, design etc.

**Comment by wellDan28** [comment]
hey @arafato, 
More documentation is always great, I can't see anything specific that I need right now,
I'll ask here if I would have any questions 
I'll start to implement the following actions:
1. [Create Table](https://docs.microsoft.com/en-us/rest/api/storageservices/create-table)
2. [Delete Table](https://docs.microsoft.com/en-us/rest/api/storageservices/delete-table)
3. [Insert Entity](https://docs.microsoft.com/en-us/rest/api/storageservices/insert-entity)
4. [Query Entities](https://docs.microsoft.com/en-us/rest/api/storageservices/query-entities)

I think that's enough for a first "table implementation PR" , other actions implementation should be in a separate PRs

**Comment by arafato** [comment]
@wellDan28 this is super cool! Will this be in-memory only or do you also plan to persist to disk? I don't have a specific opinion about that, Queue Emulator is not persisting to disk at all at the moment for example while Blob Storage does (files of course and also metadata).

**Comment by wellDan28** [comment]
I'm not sure yet, I'll update when I'll have more insights.

**Comment by pmanlukas** [comment]
@wellDan28 do you need any help with the Table Implementation? I can help you with that

**Comment by arafato** [comment]
@wellDan28 there is now actually a real customer request for table storage emulation so I'm starting implementation at https://github.com/arafato/azurite/tree/tablestorage. Once the base work is finished contributions are very much welcome. Will keep you posted here.

**Comment by wellDan28** [comment]
@pmanlukas sorry I didn't saw your message. As you can see it's not relevant until @arafato will finish the base work. thanks!

**Comment by arafato** [comment]
@wellDan28 @pmanlukas : basework is finished, feel free to grab an item :-)
