### ISSUE TITLE
Invalid case formatting on returned tags.

### ISSUE THREAD

**Issue by ekarlso** [arafato/azurite#143]
Hi the XML tags should be BlockList etc... This breaks when testing with for example client libraries..
<?xml version='1.0'?>
<blocklist>
    <committedblocks/>
    <uncommittedblocks/>
</blocklist>

**Comment by arafato** [comment]
@ekarlso thanks for reporting! Can you please give me more details on the SDK you are using and API calls you are encountering problems with? Thanks!

**Comment by arafato** [comment]
@ekarlso no need to answer above question, confirmed as bug, will provide a fix with version 1.8.4 asap.

**Comment by arafato** [comment]
@ekarlso just released fix as v1.8.4
