### ISSUE TITLE
prefix option in list blobs doesn't work as expected

### ISSUE THREAD

**Issue by m-chele** [arafato/azurite#145]
The "prefix" option used in `listBlobs(request, query)` function performs a "contains" with this instruction:  `'name': { '$contains': query.prefix }` instead it should do something like a "start_with".
I think also `listContainer` can be affected but I didn't verify.

**Comment by arafato** [comment]
@m-chele thanks for reporting! Confirmed as bug. Will roll out fix with v1.8.4 asap. Will keep you posted here.

**Comment by arafato** [comment]
@m-chele just released fix as v1.8.4
