### ISSUE TITLE
CORS - Enabling the allowing of origins so BLOBS can be displayed from browsers

### ISSUE THREAD

**Issue by jimmacb** [arafato/azurite#156]
I have looked through the code and I can't easily see how I can configure Access-Control-Allow-Origin: header on responses so I can test local browser selections for unsecured / public blobs.

Any ideas as this would normally be achieved by setting the blob service properties which aren't currently implemented?

Thanks

**Comment by arafato** [comment]
Hi @jimmacb ! This feature is currently not supported by Azurite. Happy to implement it and put in top of the backlog. Expect a working version within the next few days, will update you here.

**Comment by arafato** [comment]
@jimmacb just released `v1.9.0` which brings support for Get/Set StorageServiceProperties, Preflight Request, and CORS support. So you need to activate CORS via an according call to SetStorageServiceProperties (https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-service-properties). Then, once you set the origin header on your request, the response will include headers like `access-control-allow-origin` etc. (if a match with the specified CORS rules is found).
Let me know if it works for you.
