### ISSUE TITLE
Container creation allows illegal characters

### ISSUE THREAD

**Issue by thisisthekap** [arafato/azurite#158]
When creating containers, azurite allows e.g. underscores, which are prohibited when creating a container at Azure Blob Storage.

**Comment by arafato** [comment]
Provide validation module according to spec @ https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata

**Comment by arafato** [comment]
@thisisthekap thanks for reporting this! Fix is released as part of `v1.9.2`.
