### ISSUE TITLE
Add support for $ prefixed container names (like $root)

### ISSUE THREAD

**Issue by SimonLuckenuik** [arafato/azurite#160]
Currently, when trying to create a container with $ in front of the name, the server rejects it with error 400. $root is a well known supporter container.

More information on the $root container:
https://docs.microsoft.com/en-us/rest/api/storageservices/working-with-the-root-container

**Comment by arafato** [comment]
Hi @SimonLuckenuik ! Thanks for reporting this! Confirmed as bug / missing feature. Currently, Azurite does not support the `$root` container semantics. Will release a fix as part of `v.2.2.2` within the next couple of days. Will keep you posted about the progress here.

**Comment by SimonLuckenuik** [comment]
FYI my workaround for now has been to add manually the container in the JSON file. I eas able to add the $logs container that way and have the storage explorer working as well.

**Comment by arafato** [comment]
Cross-referencing #155 regarding `$logs` container and storage explorer integration

**Comment by arafato** [comment]
@SimonLuckenuik just released `v2.2.2`. let me know if it works for you!
