### ISSUE TITLE
Blob ETag not being returned to C# client

### ISSUE THREAD

**Issue by dsarfati** [arafato/azurite#165]
When using the c# nuget package WindowsAzure.Storage v8.6.0 connected to azurite running on OSX, the ETag property is not being populated and returns as a null string. 

Are ETags currently supported?

**Comment by arafato** [comment]
Hi @dsarfati ! Thanks for reporting. ETags should be supported. 
Can you please provide some more details: which API call / method calls are you using? Thanks!

**Comment by dsarfati** [comment]
Here is how I save the images to blob.

```
var blob = container.GetBlockBlobReference(imagePath);

blob.Properties.ContentType = "image/jpeg";

await blob.UploadFromStreamAsync(stream);
```

Here is the code to get the image back out.

```
var blob = container.GetBlockBlobReference(imagePath);

var stream = await blob.OpenReadAsync();

return new ImageContent
{
   Stream = stream,
   LastModified = blob.Properties.LastModified,
   ETag = blob.Properties.ETag,
   ContentType = blob.Properties.ContentType,
};
```

As I mentioned, `blob.Properties.ETag` is null

**Comment by arafato** [comment]
@dsarfati confirmed. This is strange since the ETag value is actually returned by Azurite but for some reason the SDK does not initialize the ETag value. Will investigate further and let you know asap here.

**Comment by dsarfati** [comment]
Thanks. I really appreciate the help!

**Comment by arafato** [comment]
@dsarfati just released `v2.4.1` which fixes the bug. The ETag needs to be enclosed by escaped double parenthesis. While some SDKs such as Node don't care, the .NET SDK will ignore the value if it is not properly enclosed. Let me know if it does not work for you.

**Comment by dsarfati** [comment]
Awesome. I will give this a try and let you know I have any more problems. Thanks again.

**Comment by arafato** [comment]
@dsarfati yes, that is the expected format. See also https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob-properties for example:
`The ETag contains a value that you can use to perform operations conditionally. See Specifying Conditional Headers for Blob Service Operations for more information. If the request version is 2011-08-18 or newer, the ETag value will be in quotes.`

Was meaning double quotes not double parenthesis, sorry!
