### ISSUE TITLE
Precondition Failed (412) when reading from blob 

### ISSUE THREAD

**Issue by dsarfati** [arafato/azurite#166]
I am getting a pre-condition failed when trying to read an image from blob.

Here is how I save the images to blob.

Here is the code to get the image out.

```
var blob = container.GetBlockBlobReference(imagePath);

var stream = await blob.OpenReadAsync();
```

The exception is thrown when I try and read the stream. This is the log for the single read event.

```
PUT /devstoreaccount1/app-icons?restype=container 409 0.549 ms - 146
HEAD /devstoreaccount1/app-icons/6204a98b-661a-4945-a09b-8d2d01035489.jpg 200 0.399 ms - 91880
GET /devstoreaccount1/app-icons/6204a98b-661a-4945-a09b-8d2d01035489.jpg 412 0.650 ms - 187
```

 I looked into the azurite code and found where the headers are being checked:

https://github.com/arafato/azurite/blob/d1861c298a0e916f44cf1f73a6db2e3ea251877c/lib/validation/blob/ConditionalRequestHeaders.js#L51-L54 

I'm not sure which conditional headers are being populated since I'm not specifying anything. It might be possible that the default C# client has some preconditions?

**Comment by arafato** [comment]
@dsarfati confirmed, fixed, and released as `v2.5.1`. Same issue (etag was not enclosed in double parenthesis). Let me know if it works for you.

**Comment by dsarfati** [comment]
@arafato Great! Did you see my comment on #165 regarding etag format?

**Comment by arafato** [comment]
@dsarfati yes, just answered. :-)
