### ISSUE TITLE
Help getting started

### ISSUE THREAD

**Issue by fmarczin** [arafato/azurite#25]
Could you add some documentation (or pointers to existing documentation) that explains how to connect to the local server?

I'm looking at this for example: https://docs.microsoft.com/en-us/azure/storage/storage-python-how-to-use-blob-storage, and I can't find a way to tell the client to connect to anything else but the real Azure services.

**Comment by arafato** [comment]
Hi @fmarczin! For python, you connect to the local storage emulator as follows:
```
from azure.storage import CloudStorageAccount
from azure.storage.blob import BlockBlobService
import io

def test():
    account = CloudStorageAccount(is_emulated=True)
    s = account.create_block_blob_service() 
    s.create_container('testcontainer')
```
