### ISSUE TITLE
Published package has `\r` line ending for script which breaks shebang

### ISSUE THREAD

**Issue by glenjamin** [arafato/azurite#32]
I tried to send a pull request to fix this, but I think my git settings did an autoconvert of the line ending.

When I install globally on my mac and try and run the app I get the following error:
```
env: node\r: No such file or directory
```

Would you be able to republish a new version with a `\n` unix line ending?

**Comment by arafato** [comment]
Interesting. Currently it's set to \r\n which works fine on Windows and Linux (Ubuntu). I will set it to `\n` only and check whether it still works on both platforms. If it does I will republish and let you know asap.

**Comment by arafato** [comment]
Published fix (?) with 0.6.7. Can you please check whether it works on Mac? Still works on Windows and Linux.

**Comment by glenjamin** [comment]
Working perfectly - thanks! 👍
