### ISSUE TITLE
List Blobs does not return Content-Length

### ISSUE THREAD

**Issue by juulhobert** [arafato/azurite#49]
Azurite does not set the Content-Length in the List Blobs response. Annoyingly this causes a crash in the "microsoft/windowsazure" package for PHP.

Response docs: https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs

**Comment by arafato** [comment]
Hi @juulhobert, can you

**Comment by arafato** [comment]
Hi @juulhobert, `Content-Length` should be set now in List Blobs Response. Can you please check? Thanks!
