### ISSUE TITLE
Add support for Service SAS

### ISSUE THREAD

**Issue by arafato** [arafato/azurite#60]
See https://docs.microsoft.com/en-us/rest/api/storageservices/constructing-a-service-sas for specification.

**Comment by gigaSproule** [comment]
Trying to be helpful, I've started work on this already on my fork (as well as issue #59). I was going to create a PR after I updated the tests (I wrote some tests against the emulator as part of another project and then made this match those tests). However, I've noticed that there are inconsistencies between the Java and Node SDK's and then there are also differences to the documentation as well. If you want, I can create a PR into a branch and you can continue on that if you wish (I'm sure you can write it in a nicer way than I have).

**Comment by arafato** [comment]
@gigaSproule This is great! Really appreciate your efforts here. Really excited to see your PR once you're ready. :-)

**Comment by thisisthekap** [comment]
@gigaSproule How far did you already get? I am asking because it is a while since you announced your PR, and I want to make sure that we are not waiting for something already abandoned.

**Comment by gigaSproule** [comment]
Hey, I did get something working, but I'm not going to say it's great code...
I was originally doing this for work, but due to one reason or another, the work got moved to another team so I never managed to have time to carry it on with my out of work commitments. I can submit a PR into a branch if you want? At least then it will allow you to take over something.

**Comment by arafato** [comment]
Hi everybody, 
the code base has massively changed since @gigaSproule forked Azurite and started implementing #60. @thisisthekap If this is a feature you need, I'm happy to prioritise it. I will reuse parts of the code that @gigaSproule has already written. Give me two weeks, I'll update you here once the feature has been implemented.

**Comment by gigaSproule** [comment]
@arafato As I said before, the code isn't pretty as I never got round to cleaning it up or dealing with every edge case. However, it should be a good starting point. Just so you are aware, to figure out the correct behaviour, I had the azure storage emulator running and used it's responses as a guide for the behaviour.

**Comment by arafato** [comment]
@gigaSproule @thisisthekap just published support for service-level SAS as v1.7.0. Hope you like it :-)

**Comment by thisisthekap** [comment]
Thanks you very much for your effort. Nevertheless, I think some parts are not working flawlessly. I just created #124 to track the issue I experienced.

**Comment by gigaSproule** [comment]
Good work guys. Sorry I wasn't able to get any further than I did.

@thisisthekap unfortunately, I can see this being a never ending issue unless Microsoft finally provide an official alternative to this :(

**Comment by arafato** [comment]
@gigaSproule I think it works now for most of the scenarios. The problem is when you are using Microsoft's SDKs to generate the signature. You can't really specify the version to use. Depending on the SDK version it will use different versions and you can't override. See https://github.com/Azure/azure-storage-node/issues/382 for details. This is why in Azurite we are now generating the signature by ourselves to be able to specify the exact version.
