### ISSUE TITLE
Empty directories don't get removed with the last file

### ISSUE THREAD

**Issue by pskorupinski** [arafato/azurite#61]
Not sure if this is a bug or a feature but, in order to perfectly emulate Azure Blobs, one could be checking if the directory is not becoming empty on file removal.

**Comment by arafato** [comment]
@pskorupinski thanks for pointing this out! Can you please give me a little bit more detail on where and how you are experiencing this kind of behaviour / error. 

- In the Azurite workspace (aka `__blobstorage__/blobs/mycontainer/myEmptyDirectory`)? 
- Or do you see this behaviour when interacting with Azurite via API calls / SDKs?

Thanks!

**Comment by arafato** [comment]
Closing this issue since lack of further information. @pskorupinski feel free to re-open this issue anytime and provide some more information (see above).

**Comment by pskorupinski** [comment]
Hello @arafato, sorry, I have missed you comment a month ago.

As far as I remember, I have seen it in the Azurite workspace. I had an assertion in a test whether the directory disappeared in filesystem and, well, it was failing.
