### ISSUE TITLE
Publish image on https://hub.docker.com/

### ISSUE THREAD

**Issue by binout** [arafato/azurite#77]
It seems you have already a docker account 

https://hub.docker.com/u/arafato/

Can you publish an image for azurite ?

Thanks

**Comment by binout** [comment]
Someone already push an image

https://hub.docker.com/r/mpahk/azurite/

**Comment by arafato** [comment]
@binout not sure if mpak hosts the latest image. I will provide an always updated image at my personal docker account @ https://hub.docker.com/u/arafato/ 

Give me some days, I'm currently refactoring large parts of the code base. I will update you here once I have integrated the docker image creation into my CI/CD pipeline.

**Comment by arafato** [comment]
@binout just published the most current version to https://hub.docker.com/u/arafato/ and integrated the whole process into my release pipeline. 
So every new release will be automatically published to my docker repo. The latest release will be always tagged as `:latest` in addition to the current version number.

**Comment by binout** [comment]
Thx !
