### ISSUE TITLE
Line endings format is broken on unix systems

### ISSUE THREAD

**Issue by d-dizhevsky** [arafato/azurite#84]
Just installed 0.9.12 version on Mac and noticed that `azurite` command gives me an error

> env: node\r: No such file or directory

I had to downgrade to 0.9.0 to get this fixed. (tried 0.9.11 but the issue appeared there as well). [Looks similar to issue #32 ](32)

**Comment by arafato** [comment]
@d-dizhevsky changed CRLF to LF line ending again. Sorry, somehow CRLF slipped back into the code. Published v0.9.13 which should work now on your system.
